name=input("enter name:")
age=input("enter the age")
price=float(input("enter the price:"))
number=list(map(int,input("enter your numbers:").split()))
number1=set(map(int,input("enter your numbers:").split()))
number2=tuple(map(int,input("enter your numbers:").split()))
number3=list(map(float,input("enter your numbers:").split()))
number4=set(map(float,input("enter your numbers:").split()))
number5=tuple(map(float,input("enter your numbers:").split()))
print(name)
print(age)
print(price)
print(number)
print(number1)
print(number2)
print(number3)
print(number4)
print(number5)


